### ISSUE TITLE
Headphone Jack

### ISSUE THREAD

**Issue by jlobodroid** [TechMangaOfficial/Dell_Latitude_5480_Hackintosh#2]
Hi, first thanks a lot for this EFI, I had a OS crack in my 5480 and in Monterrey I had some issues to update MSOffice, I did an upgrade to Sonoma and it is great, I am testing after some adjusts and Headphone Jack is not working, I tested the phone and is ok, I insert a USB phone and is ok, but P2 plug is not, any suggestion or guidance to find the problem?
When a insert the plug I can hear a small piece of sound, less than a second
tks

**Comment by jlobodroid** [comment]
I was searching about combo jack in hackintosh and find this doc
https://olarila.com/topic/40037-how-to-enable-combojack-in-hackintosh/

I did the kext insert and now everything is ok

**Comment by TechMangaOfficial** [comment]
sorry, i was little off with all this due to my exams. Thanks For the solution
